Repository Parallel-in-Time/pySDC, pull requests merged in 2024-06, with the labels that each got.

#438 Minor cleanup in datatypes
  etc/environment-pytorch.yml
  pySDC/implementations/datatype_classes/mesh.py
  pySDC/playgrounds/ML_initial_guess/tensor.py
  pySDC/tests/test_datatypes/test_datatypes.py
Labels: girl scout rule

#441 Fix Gitlab-CI
  .github/workflows/gitlab_ci.yml
  .gitlab-ci.yml
Labels: gitlab-mirror

#449 Fix for #448 and migration to scipy 1.14
  .github/workflows/ci_pipeline.yml
  README.md
  pySDC/implementations/convergence_controller_classes/store_uold.py
  pySDC/implementations/problem_classes/AllenCahn_1D_FD.py
  pySDC/implementations/problem_classes/AllenCahn_2D_FD.py
  pySDC/implementations/problem_classes/Boussinesq_2D_FD_imex.py
  pySDC/implementations/problem_classes/NonlinearSchroedinger_MPIFFT.py
  pySDC/implementations/problem_classes/Quench.py
  pySDC/implementations/problem_classes/boussinesq_helpers/standard_integrators.py
  pySDC/implementations/problem_classes/generic_ND_FD.py
  pySDC/implementations/sweeper_classes/generic_implicit_MPI.py
Labels: fix
