Repository Parallel-in-Time/pySDC, pull requests merged in 2024-07, with the labels that each got.

#456 Handle SLURM issues
  .gitlab-ci.yml
  etc/check_node_avail.sh
Labels: gitlab-mirror

#452 FrozenClass performance fix
  pySDC/helpers/pysdc_helper.py
  pySDC/tests/test_helpers/test_frozen_class.py
Labels: fix

#465 Small fixes
  pySDC/implementations/controller_classes/controller_nonMPI.py
  pySDC/implementations/problem_classes/AllenCahn_2D_FFT.py
  pySDC/implementations/problem_classes/AllenCahn_MPIFFT.py
Labels: girl scout rule, fix
